Azure/RAI-vNext-Preview

- azuredevops/templates/obtain-workspace-run-tests-step-template.yaml
- scripts/register_azureml.py
Converting the script which registers environments, components and datasets to be Python. Although Powershell is available on other platforms, if we're going to ship this, then a Python script is friendlier.
> Convert AzureML registration script to Python

- scripts/Obtain-Workspace.ps1
Tweak the script which obtains a workspace for the builds, to ensure that they are sorted. This in turn ensures that the newest workspace will always be picked.
> Sort workspaces

- config.json
- src/responsibleai/rai_analyse/constants.py
- src/responsibleai/rai_analyse/create_causal.py
- src/responsibleai/rai_analyse/create_counterfactual.py
- src/responsibleai/rai_analyse/create_error_analysis.py
- src/responsibleai/rai_analyse/create_explanation.py
- src/responsibleai/rai_analyse/create_rai_insights.py
- src/responsibleai/rai_analyse/gather_rai_insights.py
- src/responsibleai/rai_analyse/rai_component_utilities.py
Change the output of the RAI Constructor component.
Previously, the output of the Constructor was the result of calling `RAIInsights.save()`. This meant that any special handling (especially for the supplied model) would only be possible within the Constructor; thereafter, the model would be pickled and passed along to the subsequent components for use.
This changeset makes the Constructor copy its inputs (the model information file and the two datasets) to its output, and add in a JSON serialisation of the inputs parameters (such as the list of categorical features). Each individual tool component can use this to create its own `RAIInsights` object, and then work as before. The `Gather` component also requires some small changes.
> Adjust output of the Constructor component

- src/responsibleai/conda_envs/python-aml-rai.yaml
This PR adds raiwidgets as dependency for conda env.
The reason is, for AML interactive dashboard, if we use the docker container inside compute instance, we have dependency on raiwidgets to run `from raiwidgets import ResponsibleAIDashboard
ResponsibleAIDashboard(rai_i)`;
> Add raiwidgets as dependency for conda env

- src/responsibleai/conda_envs/python-aml-rai.yaml
There is an issue when we run `from raiwidgets import ResponsibleAIDashboard`: `ImportError: cannot import name 'soft_unicode' from 'markupsafe' in Release 1.38.0`
The root cause is that, there is a breaking change for `MarkupSafe:2.1.0` where they have removed `soft_unicode`.
Release note: https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0
Downgrading markupsafe to version 2.0.1 fixes the issue. So we add markupsafe<=2.0.1 to aml-rai-environment list to resolve the error.
https://github.com/aws/aws-sam-cli/issues/3661
> Add markupsafe<=2.0.1 to aml-rai-environment list

- src/responsibleai/conda_envs/python-aml-rai.yaml
This PR pins itsdangerous to version 2.0.1.
The import failure seems to be related with the latest release version of the package itsdangerous. Check the latest releases [here](https://pypi.org/project/itsdangerous/#history)
[ImportError: cannot import name 'json' from itsdangerous](https://stackoverflow.com/questions/71189819/python-docker-importerror-cannot-import-name-json-from-itsdangerous)
> Pin itsdangerous package to version 2.0.1

- src/responsibleai/responsibleai-environment.yaml
This PR add immutable tag to base image so we can reuse the derived image. Without the immutable tag, any update to the base image will invalidata the derived image name and we will not be able to pull the docker image.
For tags, we can pick any but latest from below. We picked the most recent tag: "20220303.v1"
(curl https://mcr.microsoft.com/v2/azureml/openmpi3.1.2-ubuntu18.04/tags/list).Content
{
"name": "azureml/openmpi3.1.2-ubuntu18.04",
"tags": [
"20200423.v1",
"20200723.v1",
"20200817.v1",
"20200821.v1",
"20201019.v1",
"20201113.v1",
"20201211.v1",
"20210104.v1",
"20210129.v1",
"20210220.v1",
"20210301.v1",
"20210507.v1",
"20210513.v1",
"20210531.v1",
"20210615.v1",
"20210701.v1",
"20210714.v1",
"20210727.v1",
"20210806.v1",
"20210906.v1",
"20210922.v1",
"20211005.v1", …
> Pin immutable tag to base image

- examples/notebooks/responsibleaidashboard-housing-classification-model-debugging.ipynb
- test/rai/pipeline_adult_analyse.yaml
- test/rai/pipeline_boston_analyse.yaml
- test/rai/test_causal_component.py
- test/rai/test_counterfactual_component.py
- test/rai/test_erroranalysis_component.py
- test/rai/test_rai_gather_errors.py
- test/rai/test_rai_pipeline.py
- test/rai/test_tabular_datasets.py
There is an issue making copies of the incoming data when the datasets are present via `ro_mount`. The files are copied via `shutil.copytree()` and something inside that code is getting confused. Since the current approach is going to be retired once `MLTable` comes online, just switch to `download` mode for now.
> Pipeline fixes for v2.1.2

- test/rai/pipeline_adult_analyse.yaml
- test/rai/pipeline_boston_analyse.yaml
In up-coming SDK change, pipeline yaml file job name needs to be a python identifier, I only find two yaml files that need to change in RAI repo, please modify related files if I missed.
> refine job name due to upcoming breaking change

- test/conftest.py
- test/rai/pipeline_adult_analyse.yaml
- test/rai/pipeline_boston_analyse.yaml
- test/rai/test_causal_component.py
- test/rai/test_counterfactual_component.py
- test/rai/test_erroranalysis_component.py
- test/rai/test_mini_sdk.py
- test/rai/test_rai_gather_errors.py
- test/rai/test_rai_pipeline.py
- test/rai/test_tabular_datasets.py
- Old version "JobInput" is now replaced by "Input".
- Input default type is "uri_folder", as test data are registered as "uri_file", type="uri_file" need to be specified in Input initialization.
> Change "JobInput" to "Input" due to SDK change

- requirements-dev-releasepackage.txt
Since the 'dev' builds are green, update what is considered the 'release' version of the `azure-ml` SDK.
> Update 'release' package version

- src/responsibleai/component_causal.yaml
An extraneous 'a' had inserted itself.
> Tweak display name of causal component

- test/rai/pipeline_fetch_tabular.yaml
- test/rai/test_rai_pipeline.py
- test/rai/test_tabular_datasets.py
- test/utilities_for_test.py
Extend an existing test to repeat the final experiment using a YAML. This is mainly so that we have YAML samples for the 'Fetch Registered Model" and "TabularDataset to Parquet" components.
> Add pipeline YAML for fetching models and converting datasets

- src/responsibleai/rai_analyse/_score_card/regression_components.py
fix typo in metric explanation text, sqaured should be squared
> fix typo in metric explanation text

- src/responsibleai/conda_envs/python-aml-rai.yaml
- src/responsibleai/docker_env/Dockerfile
The latest release of protobuf appears to be causing trouble for mlflow. Upper bound for now, pending fix (probably from `mlflow`).
> Protobuf upper bound

- test/rai/test_arg_helpers.py
Start to add unit tests of the various argument parsers. These are not yet comprehensive, but represent a start on the process.
> Adding parser tests

- src/responsibleai/docker_env/Dockerfile
This PR adds pre release version of azure-ai-ml package to RAI docker file. Azure-ai-ml package is required for UI side to connect RAI components to compute instance. So we add the azure-ai-ml package in the docker file.
> Add pre release azure-ai-ml package to RAI docker file

- requirements-for-testing.txt
- src/responsibleai/rai_analyse/_score_card/classification_components.py
- src/responsibleai/rai_analyse/_telemetry/_loggerfactory.py
- test/rai/test_logger_factory.py
This extracts the full traceback, sample extracted traceback (with "\n".join() )
<class 'ValueError'>
File "main.py", line 28 in test_expect_full_stack_trace_do_not_contain_secret_value
self.level_0()
File "main.py", line 17 in level_0
self.level_1()
File "main.py", line 20 in level_1
self.level_2()
File "main.py", line 23 in level_2
raise ValueError(f"{self.secret_string}")
Notice how exception message is retained without resolving, thus no runtime data are leaked.
> Improve stack trace logging

- src/responsibleai/rai_analyse/create_rai_insights.py
Customer was seeing that even when they set use_model_dependency=True we were still installing the dependencies.  It seems to be a bug in how the bool argument is defined.
> fix use_model_dependency always evaluating to true even when set to false

- src/responsibleai/docker_env/Dockerfile
Score card component is failing in test "test_boston_pipeline_from_yaml" with the error:
```
Traceback (most recent call last):
File "create_score_card.py", line 295, in <module>
main(get_parser().parse_args())
File "/mnt/azureml/cr/j/47aea72509c5452fb23c5a4cdefed485/exe/wd/_telemetry/_loggerfactory.py", line 149, in wrapper
return func(*args, **kwargs)
File "create_score_card.py", line 202, in main
wf.generate_pdf()
File "create_score_card.py", line 254, in generate_pdf
to_pdf(
File "/mnt/azureml/cr/j/47aea72509c5452fb23c5a4cdefed485/exe/wd/_score_card/common_components.py", line 841, in to_pdf
pdfkit.from_string(
File "/azureml-envs/responsibleai-0.24/lib/python3.8/site-packages/pdfkit/api.py", line 75, in from_string
return r.to_pdf(output_path)
File …
```
> pin libffi to 3.3 to fix libgobject undefined symbol ffi_type_uint32 error in score card

- examples/notebooks/responsibleaidashboard-housing-decision-making.ipynb
So far, the scorecard metrics were classification metrics leading to a validation error during execution. Changing to regression metrics fixes the problem.
Duplicate of https://github.com/Azure/azureml-examples/pull/2076
Couldn't open the PR from a branch off of this repo since I'm not part of the required group (yet). That's why it's from my fork. If that's a problem I'll create a new PR once I have access.
> RAI housing decision making notebook: Change metrics to regression metrics

- src/responsibleai/rai_analyse/create_score_card.py
If `startTimeUTC` is not available in run details, then we get the current UTC time from python.
> Update create_score_card.py to get UTC start time from python

- src/responsibleai/rai_analyse/rai_component_utilities.py
Subprocess error.output could be None : https://docs.python.org/3/library/subprocess.html so when we are checking if the output contains a substring we get a type error. Check that the output is not None before checking the contents.
To address: [Bug 2271185](https://msdata.visualstudio.com/Vienna/_workitems/edit/2271185): [Live site bug]TypeError in microsoft_azureml_rai_tabular_insight_constructor
> check if error output is None

- src/responsibleai/rai_analyse/rai_component_utilities.py
The root cause is, the output of subprocess.CalledProcessError is bytes-like object, not a str. So if we want to check if certain string is in the output, we need to convert str to bytes-like object.
Here is an example:
after converting str to b'str':
> Fix [Live site bug] <class 'TypeError'> "Could not find a version that satisfies the requirement" when load mlflow model is called

- .github/workflows/python-linting.yml
- src/responsibleai/rai_analyse/create_rai_insights.py
- src/responsibleai/rai_analyse/rai_component_utilities.py
Invalid json string in input argument can cause a json decode error. For example, a json array of
'["string1", "string2"]' can be misconstructed as '[string1, string2]' causing a json decode error from None.
> Handle input json parsing error with hint to resolve issue.

- src/responsibleai/rai_analyse/rai_component_utilities.py
- test/rai/test_rai_component_utilities.py
Fix <class 'KeyError'> for File "/mnt/azureml/cr/j/[guid]/exe/wd/rai_component_utilities.py", line 69 in fetch_model_id
return model_info[DashboardInfo.MODEL_ID_KEY]
The root cause is the input json file is not in expected format, missing key "id".
The fix is check if the key exists before using it, and raise a error to indicate the issue
> Fix <class 'KeyError'> invalid json input in rai_component_utilities.py fetch_model_id()

- .gitignore
- src/responsibleai/rai_analyse/create_score_card.py
- test/components/component_train_logreg.yaml
- test/components/src_train_logreg/train.py
- test/rai/pipeline_adult_analyse.yaml
So far we had no test case with dropped features. Since there was a bug with dropped categorical features in v0.7.0 it's prudent to add a test case for this. This way, we can catch future regressions.
> Add a test case with dropped categorical features

- src/responsibleai/rai_analyse/_score_card/_rai_insight_data.py
- src/responsibleai/rai_analyse/_score_card/common_components.py
This PR adds two UserConfigValidationExceptions:
1. For [Bug 2489952](https://msdata.visualstudio.com/Vienna/_workitems/edit/2489952): [Live site bug] KeyError for func = metric_func_map[metric] in create_score_card, check if the metric is a key in metric_func_map.
2. For [Bug 2491905](https://msdata.visualstudio.com/Vienna/_workitems/edit/2491905): [Live site bug] <class 'KeyError'>for microsoft_azureml_rai_tabular_score_card component when get_model_overview, check if ModelSummary is a key in model_overview's data
> Raise validation exceptions in score card to fix KeyErrors

- examples/notebooks/responsibleaidashboard-diabetes-decision-making.ipynb
- examples/notebooks/responsibleaidashboard-diabetes-regression-model-debugging.ipynb
- examples/notebooks/responsibleaidashboard-housing-classification-model-debugging.ipynb
- examples/notebooks/responsibleaidashboard-housing-decision-making.ipynb
- examples/notebooks/responsibleaidashboard-programmer-regression-model-debugging.ipynb
This PR enables use_model_dependency flag by default for RAI sample notebooks
> Enable use_model_dependency flag by default for RAI sample notebooks

- src/responsibleai/rai_analyse/rai_component_utilities.py
conda install log invoked from subprocess.check_output() is a byte array. There are some cases where the byte array output contain non ascii characters (utf-8 decoding worked). To avoid decoding error, leaving the byte array as is for printing without decoding.
For example, a utf8 encoded byte array such as follows can still be printed:
utf8_bytearray = "source string \u20AC".encode("utf-8")
print(utf8_bytearray)
giving
b'source string \xe2\x82\xac'
> Keep install log as byte array.

- src/responsibleai/rai_analyse/rai_component_utilities.py
- test/rai/test_rai_component_utilities.py
throw user error when model input path is not found instead of file not found error; to address [Bug 2291174](https://msdata.visualstudio.com/Vienna/_workitems/edit/2291174): DPv2: FileNotFoundError seen during fetch_model_id()
> Throw userconfigvalidation error if model input path not found

- single-rai-job/src/run_rai.py
Adds the forecasting data type to the run_properties under the RAI_INSIGHTS_DATA_TYPE_KEY (same way as vision and text insights).
> Add forecasting data type

- azuredevops/Build-Update-Dev.yaml
- azuredevops/PR-Gate.yaml
- src/responsibleai/docker_env/Dockerfile
- src/responsibleai/docker_env/conda_dependencies.yaml
update RAI-vNext-Preview tabular image to be in sync with azureml-assets
This PR syncs the RAI-vNext-Preview tabular image definition to be in sync with the definition in azureml-assets repository:
https://github.com/Azure/azureml-assets/tree/main/assets/responsibleai/environments/responsibleai-ubuntu20.04-py38-cpu
including the latest gunicorn vulnerability update:
https://github.com/Azure/azureml-assets/pull/2878
This should make it more reliable to make image updates and we can be more confident that the e2e tests in this repository validate the images before we deploy them, since there are minimal tests in the azureml-assets repository.
> update RAI-vNext-Preview tabular image to be in sync with azureml-assets

- src/responsibleai/docker_env/Dockerfile
Fixes to RAI text & vision images equivalent to https://github.com/Azure/azureml-assets/pull/3356/files .
> Fix cryptography vulnerability on RAI tabular image

- requirements-dev.txt
- requirements.txt
- src/responsibleai/docker_env/Dockerfile
- src/responsibleai/docker_env/conda_dependencies.yaml
Update RAI tabular image to ubuntu 22.04
Copilot summary:
This pull request includes several updates to the Docker environment and conda dependencies for the Responsible AI project. The changes focus on updating the base image, modifying environment variables, and cleaning up the installation process.
Updates to Docker environment:
* [`src/responsibleai/docker_env/Dockerfile`](diffhunk://#diff-bfcd7f4b46ae7e1d10eea473ad0d80eaa6383f8005c6505c5dc7943ac3ad1a94L1-L20): Updated the base image from `ubuntu20.04` to `ubuntu22.04` and adjusted environment variables to use `CONDA_PREFIX` instead of `AZUREML_CONDA_ENVIRONMENT_PATH`.
* [`src/responsibleai/docker_env/Dockerfile`](diffhunk://#diff-bfcd7f4b46ae7e1d10eea473ad0d80eaa6383f8005c6505c5dc7943ac3ad1a94L34-R35): Removed the installation of …
> Update RAI tabular image to ubuntu 22.04
