src/responsibleai/component_error_analysis.yaml
src/responsibleai/rai_analyse/create_error_analysis.py

Update to `RAIInsights` object exposed new arguments. Expose these in the components.

Update components for latest RAIInsights

---

scripts/generate_registration_files.py
scripts/register_azureml.py

Add a small helper script to aid with the creation of the two JSON files required to register the RAI components.

Helper script to create config files

---

src/responsibleai/component_causal.yaml
src/responsibleai/rai_analyse/arg_helpers.py
src/responsibleai/rai_analyse/create_counterfactual.py
test/rai/test_causal_component.py
test/rai/test_counterfactual_component.py
test/rai/test_erroranalysis_component.py
test/rai/test_rai_pipeline.py

Now that core functionality seems to be stable, start adding some more tests of the components. The main goal here is to increase coverage of the argument passing and parsing. Some small issues have been found and fixed.

Additional tests

---

docs/Setup.md

The setup instructions have been simplified a little.

Update setup instructions

---

docs/PythonSDK/how-to-create-model-analysis-python.md

Redraft the doc which details how to get started using the Python SDK.

Update Python Getting Started

---

azuredevops/PR-Gate.yaml
azuredevops/templates/obtain-workspace-run-tests-step-template.yaml

Add UK South region

---

src/responsibleai/component_rai_insights.yaml
src/responsibleai/rai_analyse/create_rai_insights.py

Add the missing `classes` argument to the RAI constructor component

Add 'classes' to constructor

---

requirements-dev-releasepackage.txt
requirements-dev.txt
test/conftest.py
test/rai/test_tabular_datasets.py

As a workaround pending the figuring out of all required updates, pin to the older version of SDKv2. This is very much a get-the-build green effort.

Pin to older SDKv2

---

azuredevops/PR-Gate.yaml
azuredevops/templates/obtain-prepare-workspace-job-template.yaml
azuredevops/templates/obtain-workspace-run-tests-step-template.yaml
azuredevops/templates/python-preparation-step-template.yaml
azuredevops/templates/run-python-tests-job-template.yaml

Split the build into two stages:
- Create/obtain workspace and upload components etc.
- Run the tests
The goal is to have a single build which can run a variety of tests against the same AzureML workspace. For right now, little has effectively changed.

Split build into stages

---

azuredevops/Build-Update-Dev.yaml
azuredevops/Build-Update-Test.yaml
azuredevops/PR-Gate.yaml
azuredevops/templates/obtain-prepare-workspace-job-template.yaml
azuredevops/templates/obtain-workspace-run-tests-step-template.yaml
azuredevops/templates/python-preparation-step-template.yaml
azuredevops/templates/run-python-tests-job-template.yaml
requirements-dev-test.txt
scripts/Install-CLIv2.ps1
scripts/Run-Pip.ps1

While DPv2 is undergoing some churn, have extra builds to examine various configurations

Extra builds

---

quick-setup.bash

A version of the quick setup script in `bash`. Performs the same tasks as the Powershell one.

Setup script for bash

---

requirements-dev-releasepackage.txt

This is your sort-of-scheduled update to the pin for the 'release' version of `azure-ml`

Update release package version

---

docs/PythonSDK/how-to-create-model-analysis-python.md
examples/notebooks/responsibleaidashboard-diabetes-decision-making.ipynb
examples/notebooks/responsibleaidashboard-diabetes-regression-model-debugging.ipynb
examples/notebooks/responsibleaidashboard-housing-classification-model-debugging.ipynb
examples/notebooks/responsibleaidashboard-housing-decision-making.ipynb
examples/notebooks/responsibleaidashboard-programmer-regression-model-debugging.ipynb
requirements-dev-releasepackage.txt
requirements-dev.txt
scripts/register_azureml.py
test/conftest.py
test/rai/test_causal_component.py
test/rai/test_counterfactual_component.py
test/rai/test_rai_gather_errors.py
test/rai/test_rai_pipeline.py
test/rai/test_tabular_datasets.py
test/utilities_for_test.py

The SDKv2 package is changing name and namespace. This updates to the latest

Change of SDKv2 package

---

requirements-dev-releasepackage.txt

Update pinned version of azure-ai-ml

---

test/rai/pipeline_adult_analyse.yaml
test/rai/pipeline_boston_analyse.yaml

Put timeouts into the pipeline YAMLs used for testing.

More YAML timeouts

---

examples/notebooks/responsibleaidashboard-diabetes-decision-making.ipynb
examples/notebooks/responsibleaidashboard-diabetes-regression-model-debugging.ipynb
examples/notebooks/responsibleaidashboard-housing-classification-model-debugging.ipynb
examples/notebooks/responsibleaidashboard-housing-decision-making.ipynb
examples/notebooks/responsibleaidashboard-programmer-regression-model-debugging.ipynb

Various tweaks:
- Use `json.dumps()` for JSONifying arguments to components
- Download the scorecard PDF

Improve Notebooks

---

src/responsibleai/rai_analyse/_score_card/common_components.py
src/responsibleai/rai_analyse/_score_card/regression_components.py

Scorecard bugfixes

---

requirements-dev-releasepackage.txt

A preview version of `azure-ai-ml` is now on PyPI. Start using this in our pipelines

Start using PyPI for azure-ai-ml

---

requirements.txt

There is a new preview version out

Bump azure-ai-ml version

---

Quick-Setup.ps1
examples/notebooks/responsibleaidashboard-diabetes-decision-making.ipynb
quick-setup.bash
requirements-dev-test.txt
requirements-dev.txt
requirements.txt

There was an issue with notebooks not picking up the right kernel. Add some extra dependencies to (hopefully) deal with this. Also correct an oversight when constructing a YAML file.

Fix notebooks

---

requirements.txt

Bump SDKv2 version

---

requirements.txt

Don't seem to need `--pre` in `requirements.txt`

Preview flag not needed

---

docs/PythonSDK/how-to-create-model-analysis-python.md

One of our docs was rather outdated, and wasn't using the DSL to create a pipeline. Update using code from one of our notebooks.

Update SDK doc

---

examples/notebooks/responsibleaidashboard-programmer-regression-model-debugging.ipynb
scripts/Install-CLIv2.ps1
scripts/Register-AzureML.ps1
scripts/Run-E2E-Tests.ps1
scripts/Run-Notebook-Tests.ps1

Work to make builds more reliable, and closer to default customer experience.

Build improvements

---

quick-setup.bash
src/responsibleai/docker_env/Dockerfile

Should no longer need the pins on `itsdangerous` and `markupsafe`

Remove requirement pins

---

src/responsibleai/rai_analyse/constants.py
src/responsibleai/rai_analyse/create_rai_insights.py
src/responsibleai/rai_analyse/rai_component_utilities.py

Adding dataset id properties in gather job for UI to display dataset links.

Add datasetids properties

---

src/responsibleai/rai_analyse/_score_card/_rai_insight_data.py
src/responsibleai/rai_analyse/_score_card/classification_components.py
src/responsibleai/rai_analyse/_score_card/common_components.py
src/responsibleai/rai_analyse/_score_card/regression_components.py
src/responsibleai/rai_analyse/constants.py
src/responsibleai/rai_analyse/create_rai_insights.py
src/responsibleai/rai_analyse/create_score_card.py
src/responsibleai/rai_analyse/gather_rai_insights.py
src/responsibleai/rai_analyse/run_score_card_bootstrap.py

Bug fix sync and adding dashboard link, model id etc to scorecard

Score card update

---

src/responsibleai/rai_analyse/create_rai_insights.py
src/responsibleai/rai_analyse/rai_component_utilities.py

Mapping model input error to userconfigerror.

Add UserConfigError. Update model input error to UserConfigError

---

src/responsibleai/rai_analyse/rai_component_utilities.py

Improved error message for model loading error.

Improve error message in mlflow model loading.

---

src/responsibleai/rai_analyse/_score_card/_rai_insight_data.py
src/responsibleai/rai_analyse/_score_card/common_components.py
src/responsibleai/rai_analyse/_telemetry/_loggerfactory.py
src/responsibleai/rai_analyse/create_explanation.py
src/responsibleai/rai_analyse/create_rai_insights.py
src/responsibleai/rai_analyse/rai_component_utilities.py

Provide exceptions to both mltable loading and parquet dataset loading error if dataset input cannot be read by either methods.

Handle dataset input loading error

---

src/responsibleai/rai_analyse/create_score_card.py

Add top_n config check.

---

src/responsibleai/rai_analyse/_telemetry/_loggerfactory.py
src/responsibleai/rai_analyse/rai_component_utilities.py
test/rai/test_logger_factory.py

add traceback of cause to userconfigerror, and log them in telemetry.

Add cause to userconfigerror, and log traceback of cause.

---

requirements-dev-test.txt
requirements-dev.txt
requirements-for-testing.txt
requirements.txt
src/responsibleai/docker_env/Dockerfile

To be consistent with azureml-assets repo

Update rai package version to 0.28.0 and update dockerfile

---

src/responsibleai/docker_env/Dockerfile

bump mltable to fix cryptography vulnerability

---

test/components/component_train_decision_tree.yaml
test/components/registration_config.json
test/components/src_train_decision_tree/train.py
test/data/registration_config.json
test/data/wine/data_wine_test.yaml
test/data/wine/data_wine_train.yaml
test/data/wine/fetch_wine.py
test/data/wine/registration_config.json
test/data/wine/test/MLTable
test/data/wine/train/MLTable
test/rai/pipeline_wine_analyse.yaml
test/rai/test_rai_pipeline.py
test/rai/wine_analyse_scorecard_config/pdf_gen.json

Adding a test since we didn't have that scenario covered at all so far.
Scorecard doesn't quite work yet, so I filed a bug to fix that.

Add a multiclass test case

---

requirements-dev-test.txt
requirements-dev.txt
requirements-for-testing.txt
requirements.txt
src/responsibleai/docker_env/Dockerfile
src/responsibleai/rai_analyse/create_rai_insights.py
src/responsibleai/rai_analyse/rai_component_utilities.py

upgrade raiwidgets, responsible-ai to 0.29.0 and automl-tabular to 0.5.0

Upgrade RAI packages

---

src/responsibleai/docker_env/Dockerfile

- Updated OSS packages to 0.30.0
- Updated automl package to 0.7.0
- Updated big data package to 0.6.0

Update Dockerfile to new tabular packages

---

src/responsibleai/rai_analyse/rai_component_utilities.py

add retry logic to conda install step to improve reliability when transient network failures occur
This PR resolves the transient network failures seen during DRI in our daily runners by adding retry logic to conda install step:
```
Error message:
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <[https://conda.anaconda.org/conda-forge/noarch/repodata.json>](https://conda.anaconda.org/conda-forge/noarch/repodata.json%3E)
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/conda-forge/noarch'
ERROR:/mnt/azureml/cr/j/03a943c9696e4fb8860a915f0a15cc0d/exe/wd/rai_component_utilities.py:Installing dependency using conda.yaml from mlflow model failed: b'Retrieving …
```

add retry logic to conda install step to improve reliability when transient network failures occur

---

src/responsibleai/docker_env/Dockerfile
src/responsibleai/docker_env/conda_dependencies.yaml

sync image dockerfile with repo azure/azureml-assets

sync image dockerfile with repo azure/azureml-assets

---

requirements-dev.txt
requirements.txt

Fix rai-vnext-preview CI build errors
This pull request updates the version of the `azure-ai-ml` package in the `requirements-dev.txt` file. The change upgrades the dependency from version `1.25.0` to `1.28.0` to ensure compatibility with the latest features and bug fixes.

Fix rai-vnext-preview CI build errors
